---
name: 'linter'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x

      - name: restore npm cache
        uses: c-hive/gha-npm-cache@v1

      - name: installing dependencies
        run: npm ci

      - name: check format
        run: npm run format-check

      - name: run lint
        run: npm run lint
